# Generated by Django 5.0 on 2024-12-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklist',
            old_name='name',
            new_name='title',
        ),
    ]
