# Generated by Django 5.0 on 2024-12-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_name_booklist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarytransaction',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='librarytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned')], db_index=True, max_length=8),
        ),
    ]
